spring:
  config:
    activate:
      on-profile: dev
  output:
    ansi:
      enabled: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-init-sql: SET search_path TO orca, extensions, public
  flyway:
    enabled: true
    init-sql: SET search_path TO orca, extensions, public
    create-schemas: true
    default-schema: orca
    schemas: orca
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orca

manta:
  auth:
    cookie-same-site: ${AUTH_COOKIE_SAME_SITE:None}
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
