spring:
  config:
    activate:
      on-profile: prod
  output:
    ansi:
      enabled: never

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-init-sql: SET search_path TO orca, extensions, public
  flyway:
    enabled: true
    init-sql: SET search_path TO orca, extensions, public
    create-schemas: true
    default-schema: orca
    schemas: orca
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orca

manta:
  auth:
    issuer: ${AUTH_JWT_ISSUER}
    audience: ${AUTH_JWT_AUDIENCE}
    jwt-secret: ${AUTH_JWT_SECRET}
    frontend-callback-uri: ${AUTH_FRONTEND_CALLBACK_URI}
  oauth:
    google:
      client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}
    kakao:
      client-id: ${KAKAO_OAUTH_CLIENT_ID}
      client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
      redirect-uri: ${KAKAO_OAUTH_REDIRECT_URI}
